### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by GrahamCampbell** [igorsantos07/yii-whoops#1]
Package versions should not be specified in composer.json files. They should be specified via git tags.

**Comment by denis-sokolov** [comment]
Perhaps "should" is a slightly strong word, but it's indeed a much more convenient way that helps avoid complications.

**Comment by igorsantos07** [comment]
I completely agree with you. On the other hand, this was made in a couple
of hours and I simply followed the Whoops suggestion. Will look at this on
the next release :)

**Comment by denis-sokolov** [comment]
Could you clarify the "Whoops suggestion"?

**Comment by igorsantos07** [comment]
The part that explains how to contribute framework integrations. The sample composer file includes versioning :)

**Comment by denis-sokolov** [comment]
Oh, thanks. Now I was able to [fix it](https://github.com/filp/whoops/commit/ae05259236204ccf904a94e5b0d96df8d4351da5)!

**Comment by igorsantos07** [comment]
So cool to see cool, happy developers around (:
This should be more common nowadays :sigh:
